### ISSUE TITLE
✨ 게시글 작성

### ISSUE THREAD

**Issue by hangnik** [FRONTENDSCHOOL7/final-06-jubging#100]
# 📑 Description
게시글 작성

# 📝 Todo
- [x] 글이 입력되거나 사진 업로드하면 버튼 활성화
- [x] 버튼 누르면 게시글 업로드
- [x] 우측 하단 버튼 누르면 사진 등록

# 📍 ETC
기타사항
