### ISSUE TITLE
✨ JSON 데이터를 활용한 채팅 목록 표시 구현

### ISSUE THREAD

**Issue by aicul313** [FRONTENDSCHOOL7/final-06-jubging#158]
# 📑 Description
JSON 데이터를 활용한 채팅 목록 표시 구현

# 📝 Todo
- [x] JSON 파일 생성
- [x] JSON 파일 로드
- [x] 채팅 목록 표시
