### ISSUE TITLE
🔨 컴포넌트 리팩토링, 컨텐츠 제목 추가

### ISSUE THREAD

**Issue by hangnik** [FRONTENDSCHOOL7/final-06-jubging#187]
# 📑 Description
헤더 컴포넌트 리팩토링, 컨텐츠 제목 추가

# 📝 Todo
- [x] 버튼 컴포넌트 리팩토링
- [x] 헤더 컴포넌트 리팩토링
- [x] 컨텐츠 제목 추가 

# 📍 ETC
기타사항
