### ISSUE TITLE
🎨 플로깅 기록 페이지 제작

### ISSUE THREAD

**Issue by hangnik** [FRONTENDSCHOOL7/final-06-jubging#212]
# 📑 Description
플로깅 기록 페이지 제작

# 📝 Todo
- [x] 네브바 게시글 등록 -> 플로깅 기록 페이지로 변경
- [x] 추천 코스 등록 -> 플로깅 기록
- [x] 게시글 작성, 플로깅 기록 작성 버튼 추가

# 📍 ETC
기타사항
