### ISSUE TITLE
🎨 게시물 상세보기, 채팅방 input 추가

### ISSUE THREAD

**Issue by hangnik** [FRONTENDSCHOOL7/final-06-jubging#76]
# 📑 Description
게시물 상세보기, 채팅방 input 추가

# 📝 Todo
- [x] 게시글, 채팅방용 input 컴포넌트 추가
- [x] 게시글 상세보기 페이지에 input 변경
- [x] 채팅룸에 input 추가

# 📍 ETC
기타사항
